### ISSUE TITLE
File and Folder Locations

### ISSUE THREAD

**Issue by kuziekj** [kylemath/Muse_LSL_Environments#1]
Downloaded this and seems to be working so far. The only issue I had was related to file and folder locations, although this is probably because I set up Chad's code first.

In the readme, might be an idea to mention which paths should be added to Matlab. Should also mention that the "muse-lsl-alexB @ 7c342b7" and "muse-lsl-matlabwrap @ 4263048" code needs to be downloaded separately since it isn't included when you download the entire "Muse_LSL_Environments" code, at least when you download the zip file.

**Comment by kylemath** [comment]
ok, so which file and folder locations were incorrect so I can fix them?

instead of downloading the code, pull the code from a repo using matlab and the tutorial in matlab I sent, and you should get those two other folders, let me know if that works,

**Comment by kuziekj** [comment]
Wasn't so much that locations were incorrect, just that  the "alexB" and "matlabwrap" folders were empty.

But yes, pulling the code with Matlab fixes all that.
